export const data = {
  "keyword": "toothbrush",
  "products": [
    {
      "id": 95133,
      "asin": "B072YVWBXH",
      "page_url": "https://www.amazon.com/dp/B072YVWBXH?tag=dwym-20&linkCode=ogi&th=1&psc=1",
      "img_small": "https://m.media-amazon.com/images/I/51NDGV7W9bL._SL75_.jpg",
      "img_medium": "https://m.media-amazon.com/images/I/51NDGV7W9bL._SL160_.jpg",
      "img_large": "https://m.media-amazon.com/images/I/51NDGV7W9bL._SL500_.jpg",
      "in_stock": 1,
      "product_condition": "New",
      "price": 39.95,
      "title": "Aquasonic Black Series Ultra Whitening Toothbrush – ADA Accepted Power Toothbrush - 8 Brush Heads & Travel Case – 40,000 VPM Electric Motor & Wireless Charging - 4 Modes w Smart Timer",
      "is_sale_price": 0,
      "basis_price": null,
      "feedback_count": 88964,
      "feedback_rating": 4.6,
      "updated_at": "2022-12-18T08:50:56.000Z",
      "created_at": "2022-04-22T11:44:07.000Z",
      "brand_id": 36355,
      "node_id": "18065351011",
      "scrapped_at": "2022-12-22T12:24:57.000Z",
      "api_access": 1,
      "priority_status": 100,
      "currency_id": 1,
      "parent_id": 100,
      "api_renewed_at": "2022-12-18T08:50:56.000Z",
      "ai_content_renewed_at": null,
      "buyable": 1,
      "color": "black",
      "weight": 0.65918216338,
      "unit_count": 1,
      "last_seen_oos": null,
      "brand": "Aquasonic",
      "pros": [
        " 40,000 VPM Smart Toothbrush – Beauty, brains and power. The Black Series is a world class modern electric toothbrush packed with the most up to date technology. It features an ultra-powerful and industry leading motor producing 40,000 vibrations per minute, a lithium-ion battery, ultra-fast wireless charging, 4 mode operation, smart vibration timers, 8 DuPont engineered brush heads, and a custom travel case; all with a sleek ultra-slim, lightweight and IPX7 rated waterproof design.  ",
        " Accepted by the American Dental Association (ADA) Council on Scientific Affairs – We put our money where your mouth is. Investing in premium oral care technologies has earned the Black Series the prestigious ADA seal of approval. It has shown efficacy in removing plaque and helping to prevent and reduce gingivitis. Black Series goes beyond just cleaning teeth – it provides complete oral care with unique modes that include one for whitening and polishing teeth, and one for improving gum health.  ",
        " Modern Tech for a Healthy Smile - Black Series brings toothbrushes into modern times with its built-in enhanced features. A lithium-ion battery, ultra-fast wireless charging (forget outdated USB charging), 4 distinct brushing modes and a smart vibrating notification timer are some of the enhanced features built into the sleek and ergonomic waterproof black satin handle.  ",
        " 8 DuPont Brush Heads & Travel Case Included – Included are 8 brush heads engineered by world famous DuPont; a world leader in quality & materials science. Each brush head lasts 3-4 months so 8 will last for about 2.5 years. Also included is a convenient custom hard shell travel case made of BPA-free plastic with space for two brush heads. Black Series can last 4 full weeks (2 min/2x a day) on a full charge so it's perfect for on the go travel with the included travel case.  ",
        " What's in the Box - 1 AquaSonic Black Series Smart Toothbrush, 1 wireless charging base, 8 DuPont brush heads, 1 travel case, warranty card, and user manual.  "
      ],
      "features": [
        "40,000 VPM Smart Toothbrush – Beauty, brains and power. The Black Series is a world class modern electric toothbrush packed with the most up to date technology. It features an ultra-powerful and industry leading motor producing 40,000 vibrations per minute , lithium-ion battery, ultra-fast wireless charging, 4 mode operation, smart vibration timers, 8 DuPont engineered brush heads and bristles, and a custom travel case; all with a sleek ultra-slim, lightweight and IPX7 rated waterproof design.",
        "Accepted by the American Dental Association (ADA) Council on Scientific Affairs – We put our money where your mouth is. Investing in premium oral care technologies has earned the Black Series the prestigious ADA seal of approval. It has shown efficacy in removing plaque and helping to prevent and reduce gingivitis. Black Series goes beyond just cleaning teeth – it provides complete oral care with unique modes that include one for whitening and polishing teeth and one for improving gum health.",
        "8 DuPont Brush Heads & Travel Case Included - Every Black Series toothbrush comes with 8 brush heads engineered by world famous DuPont; a world leader in quality & materials science. Each brush head lasts 4 months so 8 will last for over 2.5 years. Also included is a convenient custom hard shell travel case made of BPA Free plastic with space for two brush heads. AquaSonic can last 4 full weeks (2 min/2x a day) on a full charge so it's perfect for on the go travel with the included travel case",
        "Modern Tech for a Healthy Smile - Black Series brings toothbrushes into modern times with its built in enhanced features. A lithium-ion battery, ultra fast wireless charging (forget outdated USB charging), 4 distinct brushing modes and a smart vibrating notification timer are some of the enhanced features built in to the sleek and ergonomic waterproof black satin handle",
        "What's in the Box - 1 AquaSonic Black Series Smart Toothbrush, 1 wireless charging base, 8 DuPont Brush Heads, 1 Travel Case, Instruction and Support Contact Manuals"
      ]
    },
    {
      "id": 2744981,
      "asin": "B07R8WGDKF",
      "page_url": "https://www.amazon.com/dp/B07R8WGDKF?tag=dwym-20&linkCode=ogi&th=1&psc=1",
      "img_small": "https://m.media-amazon.com/images/I/41dY9OnRshL._SL75_.jpg",
      "img_medium": "https://m.media-amazon.com/images/I/41dY9OnRshL._SL160_.jpg",
      "img_large": "https://m.media-amazon.com/images/I/41dY9OnRshL._SL500_.jpg",
      "in_stock": 1,
      "product_condition": "New",
      "price": 33.95,
      "title": "AquaSonic Vibe Series Ultra Whitening Toothbrush – ADA Accepted Electric Toothbrush - 8 Brush Heads & Travel Case - Ultra Sonic Motor & Wireless Charging - 4 Modes w Smart Timer – Satin Rose Gold",
      "is_sale_price": 1,
      "basis_price": 49.95,
      "feedback_count": null,
      "feedback_rating": null,
      "updated_at": "2022-10-30T09:17:16.000Z",
      "created_at": "2022-10-11T16:52:17.000Z",
      "brand_id": 36355,
      "node_id": "18065351011",
      "scrapped_at": null,
      "api_access": 1,
      "priority_status": null,
      "currency_id": null,
      "parent_id": null,
      "api_renewed_at": "2022-10-30T09:17:16.000Z",
      "ai_content_renewed_at": null,
      "buyable": 1,
      "color": null,
      "weight": null,
      "unit_count": null,
      "last_seen_oos": null,
      "brand": "Aquasonic",
      "pros": [
        " 40,000 VPM Smart Toothbrush – Beauty, brains and power. The Vibe Series is a world class modern electric toothbrush packed with the most up to date technology. It features an ultra-powerful and industry leading motor producing 40,000 vibrations per minute , lithium-ion battery, ultra-fast wireless charging, 4 mode operation, smart vibration timers, 8 DuPont engineered brush heads, and a custom travel case; all with a sleek, ultra-slim, lightweight and IPX7 rated waterproof body.  ",
        " Accepted by the American Dental Association (ADA) Council on Scientific Affairs – We put our money where your mouth is. Investing in premium oral care technologies has earned the Vibe Series the prestigious ADA seal of approval. It has shown efficacy in removing plaque and helping to prevent and reduce gingivitis. Vibe Series goes beyond just cleaning teeth – it provides complete oral care with unique modes that include one for whitening and polishing teeth and one for improving gum health.  ",
        " 8 DuPont Brush Heads & Travel Case Included - Every Vibe Series toothbrush comes with 8 brush heads engineered by world famous DuPont; a world leader in quality & materials science. Each brush head lasts 4 months so 8 will last for over 2.5 years. Also included is a convenient custom hard shell travel case made of BPA Free plastic with space for two brush heads. AquaSonic can last 4 full weeks (2 min/2x a day) on a full charge so its perfect for on the go travel with the included travel case.  ",
        " Modern Tech For Complete Oral Care - The Vibe Series brings toothbrushes into modern times with its built in enhanced features. Ultra fast wireless charging (forget cheap USB charging), 4 distinct brushing modes and a smart vibrating notification timer are some of the enhanced features built in to the sleek waterproof and stunningly beautiful satin rose gold handle.  ",
        " What's in the Box – 1 Satin Rose Gold Smart Toothbrush, 8 DuPont brush heads, 1 custom travel case, Instruction manual, Warranty and support contact manuals.  "
      ],
      "features": [
        "40,000 VPM Smart Toothbrush – Beauty, brains and power. The Vibe Series is a world class modern electric toothbrush packed with the most up to date technology. It features an ultra-powerful and industry leading motor producing 40,000 vibrations per minute , lithium-ion battery, ultra-fast wireless charging, 4 mode operation, smart vibration timers, 8 DuPont engineered brush heads and bristles, and a custom travel case; all with a sleek ultra-slim, lightweight and IPX7 rated waterproof body.",
        "Accepted by the American Dental Association (ADA) Council on Scientific Affairs – We put our money where your mouth is. Investing in premium oral care technologies has earned the Vibe Series the prestigious ADA seal of approval. It has shown efficacy in removing plaque and helping to prevent and reduce gingivitis. Vibe Series goes beyond just cleaning teeth – it provides complete oral care with unique modes that include one for whitening and polishing teeth and one for improving gum health.",
        "8 DuPont Brush Heads & Travel Case Included - Every Vibe Series toothbrush comes with 8 brush heads engineered by world famous DuPont; a world leader in quality & materials science. Each brush head lasts 4 months so 8 will last for over 2.5 years. Also included is a convenient custom hard shell travel case made of BPA Free plastic with space for two brush heads. AquaSonic can last 4 full weeks (2 min/2x a day) on a full charge so its perfect for on the go travel with the included travel case.",
        "Modern Tech For Complete Oral Care - The Vibe Series brings toothbrushes into modern times with its built in enhanced features. Ultra fast wireless charging (forget cheap USB charging), 4 distinct brushing modes and a smart vibrating notification timer are some of the enhanced features built in to the sleek waterproof and stunningly beautiful satin rose gold handle.",
        "What's in the Box – 1 Pink Satin Rose Gold Smart Toothbrush, 8 DuPont brush heads, 1 custom travel case, Instruction manual, Warranty and support contact manuals."
      ]
    },
    {
      "id": 110962,
      "asin": "B083G7F8PG",
      "page_url": "https://www.amazon.com/dp/B083G7F8PG?tag=dwym-20&linkCode=ogi&th=1&psc=1",
      "img_small": "https://m.media-amazon.com/images/I/418Amp9nujL._SL75_.jpg",
      "img_medium": "https://m.media-amazon.com/images/I/418Amp9nujL._SL160_.jpg",
      "img_large": "https://m.media-amazon.com/images/I/418Amp9nujL._SL500_.jpg",
      "in_stock": 1,
      "product_condition": "New",
      "price": 77.94,
      "title": "AquaSonic DUO PRO – Ultra Whitening 40,000 VPM Electric Smart ToothBrushes – ADA Accepted - 4 Modes with Smart Timers - UV Sanitizing & Wireless Charging Base - 10 ProFlex Brush Heads & 2 Travel Cases",
      "is_sale_price": 1,
      "basis_price": 89.95,
      "feedback_count": 6306,
      "feedback_rating": 4.6,
      "updated_at": "2022-12-17T00:43:41.000Z",
      "created_at": "2022-04-22T11:58:18.000Z",
      "brand_id": 36355,
      "node_id": "18065351011",
      "scrapped_at": "2022-09-07T19:30:32.000Z",
      "api_access": 1,
      "priority_status": 100,
      "currency_id": 1,
      "parent_id": null,
      "api_renewed_at": "2022-12-17T00:43:41.000Z",
      "ai_content_renewed_at": null,
      "buyable": 1,
      "color": "white",
      "weight": null,
      "unit_count": null,
      "last_seen_oos": null,
      "brand": "Aquasonic",
      "pros": [
        " Pro Home & Travel System for 2 – World class oral care gets even better with Duo Pro. Duo Pro features 2 IPX7 waterproof midnight black and optic white smart toothbrushes with 40,000VPM ultrasonic motors, lithium-ion batteries (30 days on a single charge), 4 unique modes with smart timers, and true wireless charging. A new UV sanitizing and wireless charging dock with autotimer kills 99.99% of germs. Duo Pro features 10 ProFlex brush heads and 2 custom travel cases for a total of 15 items.  ",
        " Kills 99.99% of Germs with UV Sanitization – Rinsing brush heads does little to kill left over oral germs. Duo Pro solves this issue by using an auto-timed UV sanitizing chamber to kill 99.99% of germs and prevent them from multiplying before your next brushing session. The dual brush docking stations also feature true wireless charging; not cheap USB charging of competitors.  ",
        " Accepted by the American Dental Association (ADA) Council on Scientific Affairs – We put our money where your mouth is. Investing in premium oral care technologies has earned Duo Pro the prestigious ADA seal of approval. It has shown efficacy in removing plaque and helping to prevent and reduce gingivitis. Duo Pro goes beyond just cleaning teeth – it provides complete oral care with unique modes that include one for whitening and polishing teeth and one for improving gum health.  ",
        " 10 ProFlex Brush Heads & 2 Travel Cases Included – Duo Pro features Dupont engineered ProFlex brush heads that use precisely angled bristles with just the right amount of elasticity to drastically enhance cleaning and whitening. 2 color coded travel cases are included. Each Duo Pro smart brush will last a full 30 days on a single charge so no need to take your charging base on your trips.  ",
        " What's in the Box - 1 Midnight Black Smart Toothbrush, 1 Optic White Smart Toothbrush, 1 UV Sanitizing and Wireless Charging Base, 5 Midnight Black ProFlex Brush Heads, 5 Optic White ProFlex Brush Heads, 1 Midnight Black Travel Case, 1 Optic White Travel Case.  "
      ],
      "features": [
        "Pro Home & Travel System for 2 – World class oral care gets even better with Duo Pro. Duo Pro features 2 IPX7 waterproof midnight black and optic white smart toothbrushes with 40,000VPM ultrasonic motors, lithium-ion batteries (30 days on a single charge), 4 unique modes with smart timers, and true wireless charging. A new UV sanitizing and wireless charging dock with autotimer kills 99.99% of germs. Duo Pro features 10 ProFlex brush heads and 2 custom travel cases for a total of 15 items.",
        "Kills 99.99% of Germs with UV Sanitization – Rinsing brush heads does little to kill left over oral germs. Duo Pro solves this issue by using an auto-timed UV sanitizing chamber to kill 99.99% of germs and prevent them from multiplying before your next brushing session. The dual brush docking stations also feature true wireless charging; not cheap USB charging of competitors.",
        "Accepted by the American Dental Association (ADA) Council on Scientific Affairs – We put our money where your mouth is. Investing in premium oral care technologies has earned Duo Pro the prestigious ADA seal of approval. It has shown efficacy in removing plaque and helping to prevent and reduce gingivitis. Duo Pro goes beyond just cleaning teeth – it provides complete oral care with unique modes that include one for whitening and polishing teeth and one for improving gum health.",
        "10 ProFlex Brush Heads & 2 Travel Cases Included – Duo Pro features Dupont engineered ProFlex brush heads that use precisely angled bristles with just the right amount of elasticity to drastically enhance cleaning and whitening. 2 color coded travel cases are included. Each Duo Pro smart brush will last a full 30 days on a single charge so no need to take your charging base on your trips.",
        "What's in the Box - 1 Midnight Black Smart Toothbrush, 1 Optic White Smart Toothbrush, 1 UV Sanitizing and Wireless Charging Base, 5 Midnight Black ProFlex Brush Heads, 5 Optic White ProFlex Brush Heads, 1 Midnight Black Travel Case, 1 Optic White Travel Case."
      ]
    }
  ],
  "relatedKeywords": [
    "tooth brush",
    "travel toothbrush kit",
    "electric toothbrush for adults"
  ]
}